name: Setup .NET environment
description: Setup .NET environment

inputs:
  base-path:
    description: Base path to run install on
    required: false
    default: .


runs:
  using: composite
  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      working-directory: ${{ inputs.base-path }}
      shell: bash
      run: nuget restore
