name: Setup python environment
description: Setup python environment with poetry

inputs:
  base-path:
    description: Base path to run install on
    required: false
    default: .
  cache:
    description: Dependency manager to cache
    required: false
    default: yarn
  registry:
    description: Registry
    required: false


runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: ${{ inputs.registry }}
        cache: ${{ inputs.cache != 'none' && inputs.cache || '' }}
        always-auth: true

    - name: Install dependencies
      working-directory: ${{ inputs.base-path }}
      shell: bash
      run: yarn install
