name: Setup python environment
description: Setup python environment with poetry

inputs:
  base-path:
    description: Base path to run install on
    required: false
    default: .
  cache:
    description: Dependency manager to cache
    required: false
    default: poetry
  version:
    description: Version of SDK
    required: false
    default: '3.10'


runs:
  using: composite
  steps:
    - name: Install poetry.
      shell: bash
      run: pipx install poetry

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
        cache: ${{ inputs.cache != 'none' && inputs.cache || '' }}

    - name: Install dependencies
      working-directory: ${{ inputs.base-path }}
      shell: bash
      run: poetry install
