name: Setup environment
description: Setup environment per `env.BUILD_LANG`

inputs:
  base-path:
    description: Base path to run install on
    required: false
    default: .
  cache:
    description: Dependency manager to cache
    required: false
  registry:
    description: Registry
    required: false
  registry-token:
    description: Token for logging into registry
    required: false
  version:
    description: Version of SDK
    required: false


runs:
  using: composite
  steps:
    - name: Setup node
      uses: pukenicorn/gh-workflows/node/setup@main
      with:
        base-path: ${{ inputs.base-path }}
        version: ${{ inputs.version }}
        cache: ${{ inputs.cache != '' && inputs.cache || 'yarn' }}
        registry: ${{ inputs.registry }}
        registry-token: ${{ inputs.registry-token }}
      if: env.BUILD_LANG == 'node'

    - name: Setup python
      uses: pukenicorn/gh-workflows/python/setup@main
      with:
        base-path: ${{ inputs.base-path }}
        version: ${{ inputs.version }}
        cache: ${{ inputs.cache != '' && inputs.cache || 'poetry' }}
      if: env.BUILD_LANG == 'python'

    - name: Setup dotnet
      uses: pukenicorn/gh-workflows/dotnet/setup@main
      with:
        base-path: ${{ inputs.base-path }}
        version: ${{ inputs.version }}
      if: env.BUILD_LANG == 'dotnet'
