name: Checkout and publish package

on:
  workflow_call:
    inputs:
      base-language:
        description: Base language (language of codebase)
        type: string
        required: true
      base-sdk-version:
        description: Base related SDK version
        type: string
        required: false
      base-language-cache:
        description: Base language dependency manager to cache (`none`, [...package manager name...])
        type: string
        required: false
      base-registry:
        description: URL of registry for base language
        type: string
        required: false
      package-language:
        description: Package Language (language of package to be export) (Defaults to base language)
        type: string
        required: false
      package-sdk-version:
        description: Package related SDK version
        type: string
        required: false
      package-language-cache:
        description: Package language dependency manager to cache (`default`, [...package manager name...])
        type: string
        required: false
      package-path:
        description: Base path of package to be build
        type: string
        required: false
        default: .
      post-setup-command:
        description: Command to run after setup base environment (but before package env, will be append to cli of respective language)
        type: string
        required: false
      package-name:
        description: Name of exported package
        type: string
        required: false
        default: ${{ github.repository }}
      package-registry:
        description: URL of registry to export to
        type: string
        required: false
      package-version:
        description: Version of package
        type: string
        required: true
      generate-swagger:
        description: Runs generate swagger spec if true
        type: boolean
        required: false
        default: true
    secrets:
      PACKAGE_REGISTRY_TOKEN:
        description: Token for logging into registry to export to
        required: false
      PACKAGE_DEPENDENCIES_REGISTRY_TOKEN:
        description: Token for logging into registry to export to
        required: false
      PACKAGE_TARGET_REGISTRY_TOKEN:
        description: Token for logging into registry to export to
        required: false

env:
  BUILD_LANG: ${{ inputs.base-language }}


jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Normalize `version`
        id: normalize-version
        shell: bash
        run: echo normalized-version=$(sed -E 's/[^0-9.-]//g' <<< "${{ inputs.version }}") >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup for base
        uses: pukenicorn/gh-workflows/mux/setup@main
        with:
          cache: ${{ inputs.base-language-cache }}
          registry: ${{ inputs.package-language != inputs.base-language && inputs.package-registry || inputs.base-registry }}
          version: ${{ inputs.base-sdk-version != '' && inputs.base-sdk-version || inputs.base-sdk-version }}

      - name: Run post-setup command
        uses: pukenicorn/gh-workflows/mux/run-command@main
        with:
          command: ${{ inputs.post-setup-command }}
        if: inputs.post-setup-command != ''

      - name: Generate swagger
        uses: pukenicorn/gh-workflows/mux/generate-swagger@main
        with:
          base-path: ${{ inputs.package-path }}
          package-name: ${{ inputs.package-name }}
          package-version: ${{ steps.normalize-version.outputs.normalized-version }}
          package-repository: ${{ inputs.package-registry }}
        if: inputs.generate-swagger

      - name: Setup for package
        uses: pukenicorn/gh-workflows/mux/setup@main
        env:
          BUILD_LANG: ${{ inputs.package-language != '' && inputs.package-language || inputs.base-language }}
        with:
          base-path: ${{ inputs.package-path }}
          cache: ${{ inputs.package-language-cache }}
          registry: ${{ inputs.package-registry }}
          version: ${{ inputs.package-sdk-version != '' && inputs.package-sdk-version || inputs.base-sdk-version }}
        if: inputs.package-language != '' && (inputs.package-language != inputs.base-language || inputs.package-registry != inputs.base-registry)

      - name: Publish package
        uses: pukenicorn/gh-workflows/mux/publish@main
        env:
          BUILD_LANG: ${{ inputs.package-language != '' && inputs.package-language || inputs.base-language }}
        with:
          base-path: ${{ inputs.package-path }}
          name: ${{ inputs.package-name }}
          version: ${{ steps.normalize-version.outputs.normalized-version }}
          registry: ${{ inputs.package-registry }}
          registry-token: ${{ secrets.PACKAGE_DEPENDENCIES_REGISTRY_TOKEN || secrets.PACKAGE_REGISTRY_TOKEN || github.token }}
