name: Run test

on:
  workflow_call:
    inputs:
      language:
        description: Language
        type: string
        required: true

env:
  BUILD_LANG: ${{ inputs.language }}


jobs:
  init:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup workspace
        uses: pukenicorn/gh-workflows/mux/setup@main

      - name: Test
        uses: pukenicorn/gh-workflows/mux/test@main
